name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analyzing the code with pylint
        run: |
          pylint  --disable=missing-module-docstring --disable=missing-class-docstring --disable=missing-function-docstring  $(git ls-files '*.py')
